name: world-cup-predictions-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - numpy=1
  - pandas=2
  - plotly=5.24
  - pylint=3.3.3
  - streamlit=1
