name: world-cup-predictions-env
channels:
  - defaults
dependencies:
  - python=3.12
  - numpy=1
  - pandas=2
  - plotly=5.24
  - pylint=3.3.3
  - pydeck=0.8
  - streamlit=1
  - scikit-learn=1
  - joblib=1
